<?php

use Illuminate\Database\Seeder;

use App\Models\Ref\RefCurrency;

class RefCurrencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        RefCurrency::truncate();
        $currencies = [
            ["ADP","Andorran Peseta --> (Old --> EUR)"],
            ["AED","United Arab Emirates Dirham"],
            ["AFA","Afghani (Old)"],
            ["AFN","Afghani"],
            ["ALL","Albanian Lek"],
            ["AMD","Armenian Dram"],
            ["ANG","West Indian Guilder"],
            ["AOA","Angolanische Kwanza"],
            ["AON","Angolan New Kwanza (Old)"],
            ["AOR","Angolan Kwanza Reajustado (Old)"],
            ["ARS","Argentine Peso"],
            ["ATS","Austrian Schilling (Old --> EUR)"],
            ["AUD","Australian Dollar"],
            ["AWG","Aruban Florin"],
            ["AZM","Azerbaijani Manat (Old)"],
            ["AZN","Azerbaijani Manat"],
            ["BAM","Bosnia and Herzegovina Convertible Mark"],
            ["BBD","Barbados Dollar"],
            ["BDT","Bangladesh Taka"],
            ["BEF","Belgian Franc (Old --> EUR)"],
            ["BGN","Bulgarian Lev"],
            ["BHD","Bahraini Dinar"],
            ["BIF","Burundi Franc"],
            ["BMD","Bermudan Dollar"],
            ["BND","Brunei Dollar"],
            ["BOB","Boliviano"],
            ["BRL","Brazilian Real"],
            ["BSD","Bahaman Dollar"],
            ["BTN","Bhutan Ngultrum"],
            ["BWP","Botswana Pula"],
            ["BYB","Belarusian Ruble (Old)"],
            ["BYN","Belarusian Ruble (New)"],
            ["BYR","Belarusian Ruble"],
            ["BZD","Belize Dollar"],
            ["CAD","Canadian Dollar"],
            ["CDF","Congolese Franc"],
            ["CFP","French Franc (Pacific Islands)"],
            ["CHF","Swiss Franc"],
            ["CLP","Chilean Peso"],
            ["CLP4",""],
            ["CNY","Chinese Renminbi"],
            ["COP","Colombian Peso"],
            ["CRC","Costa Rica Colon"],
            ["CSD","Serbian Dinar (Old)"],
            ["CUC","Peso Convertible"],
            ["CUP","Cuban Peso"],
            ["CVE","Cape Verde Escudo"],
            ["CYP","Cyprus Pound  (Old --> EUR)"],
            ["CZK","Czech Krona"],
            ["DEM","German Mark    (Old --> EUR)"],
            ["DEM3","(Internal) German Mark (3 dec.places)"],
            ["DJF","Djibouti Franc"],
            ["DKK","Danish Krone"],
            ["DOP","Dominican Peso"],
            ["DZD","Algerian Dinar"],
            ["ECS","Ecuadorian Sucre (Old --> USD)"],
            ["EEK","Estonian Krone (Old --> EUR)"],
            ["EGP","Egyptian Pound"],
            ["ERN","Eritrean Nafka"],
            ["ESP","Spanish Peseta (Old --> EUR)"],
            ["ETB","Ethiopian Birr"],
            ["EUR","European Euro"],
            ["EUR4","European Euro"],
            ["FIM","Finnish Markka (Old --> EUR)"],
            ["FJD","Fiji Dollar"],
            ["FKP","Falkland Pound"],
            ["FRF","French Franc (Old --> EUR)"],
            ["GBP","British Pound"],
            ["GEL","Georgian Lari"],
            ["GHC","Ghanaian Cedi (Old)"],
            ["GHS","Ghanian Cedi"],
            ["GIP","Gibraltar Pound"],
            ["GMD","Gambian Dalasi"],
            ["GNF","Guinean Franc"],
            ["GRD","Greek Drachma (Old --> EUR)"],
            ["GTQ","Guatemalan Quetzal"],
            ["GWP","Guinea Peso (Old --> SHP)"],
            ["GYD","Guyana Dollar"],
            ["HKD","Hong Kong Dollar"],
            ["HNL","Honduran Lempira"],
            ["HRK","Croatian Kuna"],
            ["HTG","Haitian Gourde"],
            ["HUF","Hungarian Forint"],
            ["IDR","Indonesian Rupiah"],
            ["IEP","Irish Punt (Old --> EUR)"],
            ["ILS","Israeli Scheckel"],
            ["INR","Indian Rupee"],
            ["IQD","Iraqui Dinar"],
            ["IRR","Iranian Rial"],
            ["ISK","Iceland Krona"],
            ["ITL","Italian Lira (Old --> EUR)"],
            ["JMD","Jamaican Dollar"],
            ["JOD","Jordanian Dinar"],
            ["JPY","Japanese Yen"],
            ["KES","Kenyan Shilling"],
            ["KGS","Kyrgyzstan Som"],
            ["KHR","Cambodian Riel"],
            ["KMF","Comoros Franc"],
            ["KPW","North Korean Won"],
            ["KRW","South Korean Won"],
            ["KWD","Kuwaiti Dinar"],
            ["KYD","Cayman Dollar"],
            ["KZT","Kazakstanian Tenge"],
            ["LAK","Laotian Kip"],
            ["LBP","Lebanese Pound"],
            ["LKR","Sri Lankan Rupee"],
            ["LRD","Liberian Dollar"],
            ["LSL","Lesotho Loti"],
            ["LTL","Lithuanian Lita"],
            ["LUF","Luxembourg Franc (Old --> EUR)"],
            ["LVL","Latvian Lat"],
            ["LYD","Libyan Dinar"],
            ["MAD","Moroccan Dirham"],
            ["MDL","Moldavian Leu"],
            ["MGA","Madagascan Ariary"],
            ["MGF","Madagascan Franc (Old"],
            ["MKD","Macedonian Denar"],
            ["MMK","Myanmar Kyat"],
            ["MNT","Mongolian Tugrik"],
            ["MOP","Macao Pataca"],
            ["MRO","Mauritanian Ouguiya"],
            ["MRU","Mauritanian Ouguiya"],
            ["MTL","Maltese Lira (Old --> EUR)"],
            ["MUR","Mauritian Rupee"],
            ["MVR","Maldive Rufiyaa"],
            ["MWK","Malawi Kwacha"],
            ["MXN","Mexican Pesos"],
            ["MYR","Malaysian Ringgit"],
            ["MZM","Mozambique Metical (Old)"],
            ["MZN","Mozambique Metical"],
            ["NAD","Namibian Dollar"],
            ["NGN","Nigerian Naira"],
            ["NIO","Nicaraguan Cordoba Oro"],
            ["NLG","Dutch Guilder (Old --> EUR)"],
            ["NOK","Norwegian Krone"],
            ["NPR","Nepalese Rupee"],
            ["NZD","New Zealand Dollars"],
            ["NZD5","New Zealand Dollars"],
            ["OMR","Omani Rial"],
            ["PAB","Panamanian Balboa"],
            ["PEN","Peruvian New Sol"],
            ["PGK","Papua New Guinea Kina"],
            ["PHP","Philippine Peso"],
            ["PKR","Pakistani Rupee"],
            ["PLN","Polish Zloty (new)"],
            ["PTE","Portuguese Escudo (Old --> EUR)"],
            ["PYG","Paraguayan Guarani"],
            ["QAR","Qatar Rial"],
            ["RMB","Chinese Yuan Renminbi"],
            ["ROL","Romanian Leu (Old)"],
            ["RON","Romanian Leu"],
            ["RSD","Serbian Dinar"],
            ["RUB","Russian Ruble"],
            ["RWF","Rwandan Franc"],
            ["SAR","Saudi Riyal"],
            ["SBD","Solomon Islands Dollar"],
            ["SCR","Seychelles Rupee"],
            ["SDD","Sudanese Dinar (Old)"],
            ["SDG","Sudanese Pound"],
            ["SDP","Sudanese Pound (until 1992)"],
            ["SEK","Swedish Krona"],
            ["SGD","Singapore Dollar"],
            ["SHP","St.Helena Pound"],
            ["SIT","Slovenian Tolar (Old --> EUR)"],
            ["SKK","Slovakian Krona (Old --> EUR)"],
            ["SLL","Sierra Leone Leone"],
            ["SOS","Somalian Shilling"],
            ["SRD","Surinam Dollar"],
            ["SRG","Surinam Guilder (Old)"],
            ["SSP","South Sudanese Pound"],
            ["STD","Sao Tome / Principe Dobra"],
            ["STN",""],
            ["SVC","El Salvador Colon"],
            ["SYP","Syrian Pound"],
            ["SZL","Swaziland Lilangeni"],
            ["THB","Thailand Baht"],
            ["TJR","Tajikistani Ruble (Old)"],
            ["TJS","Tajikistani Somoni"],
            ["TMM","Turkmenistani Manat (Old)"],
            ["TMT","Turkmenistani Manat"],
            ["TND","Tunisian Dinar"],
            ["TOP","Tongan Pa'anga"],
            ["TPE","Timor Escudo --> USD"],
            ["TRL","Turkish Lira (Old)"],
            ["TRY","Turkish Lira"],
            ["TTD","Trinidad and Tobago Dollar"],
            ["TWD","New Taiwan Dollar"],
            ["TZS","Tanzanian Shilling"],
            ["UAH","Ukraine Hryvnia"],
            ["UF",""],
            ["UGX","Ugandan Shilling"],
            ["USD","United States Dollar"],
            ["USDN","(Internal) United States Dollar (5 Dec.)"],
            ["UTM",""],
            ["UYI",""],
            ["UYU","Uruguayan Peso"],
            ["UZS","Uzbekistan Som"],
            ["VEB","Venezuelan Bolivar (Old)"],
            ["VEF","Venezuelan Bolivar"],
            ["VES","Venezuelan Bolivar"],
            ["VND","Vietnamese Dong"],
            ["VUV","Vanuatu Vatu"],
            ["WST","Samoan Tala"],
            ["XAF","Gabon CFA Franc BEAC"],
            ["XCD","East Carribean Dollar"],
            ["XEU","European Currency Unit (E.C.U.)"],
            ["XOF","Benin CFA Franc BCEAO"],
            ["XPF","CFP Franc"],
            ["YER","Yemeni Ryal"],
            ["YUM","New Yugoslavian Dinar (Old)"],
            ["ZAR","South African Rand"],
            ["ZMK","Zambian Kwacha (Old)"],
            ["ZMW","Zambian Kwacha (New)"],
            ["ZRN","Zaire (Old)"],
            ["ZWD","Zimbabwean Dollar (Old)"],
            ["ZWL","Zimbabwean Dollar (New)"],
            ["ZWN","Zimbabwean Dollar (Old)"],
            ["ZWR","Zimbabwean Dollar (Old)"]
        ];

        $data = [];
        foreach($currencies as $currency){
            $data[] = [
                "currency"=>$currency[0],
                "description"=>$currency[1]
            ];
        }
        RefCurrency::insert($data);
    }
}
